### ISSUE TITLE
Recipe fails on x64 install

### ISSUE THREAD

**Issue by ChristianEnfield** [dhoer/chef-mozilla_firefox#10]
Hi,

Without having the default['mozilla_firefox']['force_32bit'] set to true, the recipe fails.
It looks as if it is still looking for the 32bit path, even on a 64bit install.

01:01:38 ==> default:   * mozilla_firefox[latest-esr] action install
01:01:38 ==> default: windows_package will be removed in the next major version release
01:01:38 ==> default: 
01:01:38 ==> default: of the Windows cookbook.
01:01:38 ==> default: 
01:01:38 ==> default: 
01:01:38 ==> default:     * windows_package[Mozilla Firefox 45.4.0 ESR (x64 en-GB)] action install
01:01:38 ==> default:     Recipe: <Dynamically Defined Resource>
01:01:38 ==> default:       * remote_file[C:\chef\cache\package\Firefox Setup 45.4.0esr.exe] action create
01:01:44 ==> default:         - create new file C:\chef\cache\package\Firefox Setup 45.4.0esr.exe
01:01:46 ==> default:         - update content in file C:\chef\cache\package\Firefox Setup 45.4.0esr.exe from none to e31325
01:01:46 ==> default:         (file sizes exceed 10000000 bytes, diff output suppressed)
01:02:15 ==> default: [2016-09-27T01:02:14+01:00] INFO: windows_package[Mozilla Firefox 45.4.0 ESR (x64 en-GB)] installed Mozilla Firefox 45.4.0 ESR (x64 en-GB) at latest
01:02:15 ==> default: 
01:02:15 ==> default:       - install version latest of package Mozilla Firefox 45.4.0 ESR (x64 en-GB)
01:02:15 ==> default:   
01:02:15 ==> default:   
01:02:15 ==> default:   ================================================================================
01:02:15 ==> default:   Recipe Compile Error in C:\vagrant-berkshelf\269a015c7626e6c66aac7be6a534eb74\cookbooks\ois_selenium_node\recipes\default.rb
01:02:15 ==> default:   ================================================================================
01:02:15 ==> default:   
01:02:15 ==> default:   Mixlib::ShellOut::ShellCommandFailed
01:02:15 ==> default:   ------------------------------------
01:02:15 ==> default:   Expected process to exit with [0], but received '255'
01:02:15 ==> default:   ---- Begin output of "C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -v | more ----
01:02:15 ==> default:   STDOUT: 
01:02:15 ==> default:   STDERR: The system cannot find the path specified.
01:02:15 ==> default:   ---- End output of "C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -v | more ----
01:02:15 ==> default:   Ran "C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -v | more returned 255

**Comment by dhoer** [comment]
Can you verify that the version you are running has this in the library?
https://github.com/dhoer/chef-mozilla_firefox/blob/master/libraries/default.rb#L8-L14

It should get caught in the rescue portion and run the non x86 path.

This really should read the registry to get the default version of firefox installed.  If you feel brave enough to submit a PR that looks at the registry and grabs the install location from there, it would be much appreciated.

The choco install give hints on what registries to read to get that info:
https://chocolatey.org/packages/Firefox

**Comment by dhoer** [comment]
This should now be fixed in 1.2.4 release. AppVeyor wasn't catching that error.  I verified that it now works on kitchen locally for both 32 and 64 bit versions.
