### ISSUE TITLE
Unable to avoid package based install on CentOS

### ISSUE THREAD

**Issue by fletchowns** [dhoer/chef-mozilla_firefox#14]
If you set `use_package_manager` to false it doesn't seem to matter for centos & rhel platforms, it will still do a package based installation. I believe it's due to the this conditional: https://github.com/dhoer/chef-mozilla_firefox/commit/c476a40fc24982d575fb8b55d68d2c7d81870a44#diff-a27dfd053e213b0e3bff4c49b8a9894eR146

**Comment by dhoer** [comment]
I backed out supporting centos because of issues.  I take it that firefox is working fine when you run it on centos?

**Comment by fletchowns** [comment]
Yup seems to work fine when I run it on centos 7. What sort of issues were you seeing?

**Comment by dhoer** [comment]
I don't remember. My integration tests would fail on centos, but not on ubuntu.

**Comment by dhoer** [comment]
I will merge this this weekend and test it out.

**Comment by fletchowns** [comment]
Sweet! I'm actually using quite a few of your cookbooks on centos 7 & rhel 7:
* mozilla_firefox
* chrome
* selenium
* selenium_grid

They have been super helpful, thank you so much for creating these!

**Comment by dhoer** [comment]
Thanks for the kudos, there was a lot of work involved in building out the selenium grid.  Release v3.0.1 should be on supermarket now.

**Comment by fletchowns** [comment]
@dhoer I can tell a lot of work was put into it, they are excellent! Thanks so much for 3.0.1, I just pulled in the new version and it's working great.
