### ISSUE TITLE
Firefox no longer installing causing Repice compile error

### ISSUE THREAD

**Issue by ChristianEnfield** [dhoer/chef-mozilla_firefox#6]
After the update to 1.2.0 we are no longer able to use the selenium_grid::node recipe as Firefox is no longer installing.
This was testing on Windows 8 provisioning with chef-solo, Ubunutu 14.04 and 16.04 through Vagrant. 

The following error is presented:

`11:15:46 ==> default:   Mixlib::ShellOut::ShellCommandFailed
11:15:46 ==> default:   ------------------------------------
11:15:46 ==> default:   Expected process to exit with [0], but received '255'
11:15:46 ==> default:   ---- Begin output of firefox -v | more ----
11:15:46 ==> default:   STDOUT: 
11:15:46 ==> default:   STDERR: 'firefox' is not recognized as an internal or external command,
11:15:46 ==> default: 
11:15:46 ==> default:   operable program or batch file.
11:15:46 ==> default:   ---- End output of firefox -v | more ----
11:15:46 ==> default:   Ran firefox -v | more returned 255`

We have switched our cookbook to use mozilla_firefox 1.1.1 and this is now working.

**Comment by dhoer** [comment]
Thanks, this is now fixed in v1.2.1
